# Generated by Django 4.2.7 on 2024-01-03 11:08

from django.db import migrations, models
import django.db.models.deletion
import faceMgt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceMgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRegistrationInformation',
            fields=[
                ('face_id', models.CharField(max_length=18, verbose_name='人脸ID')),
                ('user_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('face_reg_img', models.ImageField(upload_to=faceMgt.models.get_face_reg_file_path, verbose_name='人脸图片')),
                ('face_feature_array', models.TextField(verbose_name='人脸特征')),
                ('face_feature_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='人脸特征向量ID')),
                ('status', models.BooleanField(choices=[(0, '启用'), (1, '停用')], default=0, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('request_id', models.CharField(default='c8096153-9dd2-45a8-8460-6d1e400dc7e7', max_length=36, verbose_name='请求ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='serviceMgt.competencyregistry', verbose_name='账号')),
            ],
            options={
                'verbose_name': '人脸注册信息表',
                'verbose_name_plural': '3.人脸注册信息',
                'unique_together': {('account', 'face_id')},
            },
        ),
    ]
