# Generated by Django 4.2.7 on 2024-01-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyRegistry',
            fields=[
                ('account', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='账号')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('access_key', models.CharField(default='dl1LTnh0F5rQWCrRd3QbcV9COPrOwwKo', max_length=32, unique=True, verbose_name='AK')),
                ('secret_key', models.CharField(default='km6A1Tv9TvAxAU0yzOPNt4MknlL6Wo7v', max_length=32, unique=True, verbose_name='SK')),
                ('account_description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述')),
                ('status', models.BooleanField(choices=[(0, '启用'), (1, '停用')], default=0, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '能力注册',
                'verbose_name_plural': '1.能力注册',
            },
        ),
        migrations.CreateModel(
            name='CapabilitySubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.SmallIntegerField(choices=[(0, '人脸检测'), (1, '人脸特征提取'), (2, '人脸1:1(图像)'), (3, '人脸1:1(校验)'), (4, '人脸1:N'), (5, '静默活体检测'), (6, '人脸关键点检测'), (7, '人脸注册（库管理）')], verbose_name='能力选择')),
                ('validity_period', models.DateTimeField(verbose_name='有效期')),
                ('subscription_req_amount', models.IntegerField(default=-1, verbose_name='订阅调用量（-1为无限制）')),
                ('max_req_amount', models.IntegerField(default=-1, verbose_name='剩余调用量（-1为无限制）')),
                ('total_req_count', models.IntegerField(default=0, verbose_name='累计调用量')),
                ('status', models.BooleanField(choices=[(0, '生效'), (1, '失效')], verbose_name='能力状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceMgt.competencyregistry', verbose_name='账号')),
            ],
            options={
                'verbose_name': '能力订阅详情',
                'verbose_name_plural': '2.能力订阅详情',
                'unique_together': {('account', 'ability')},
            },
        ),
    ]
