# Generated by Django 4.2.7 on 2024-01-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceMgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencyregistry',
            name='access_key',
            field=models.CharField(default='gS5oG5acvh2jaeUzEATX9EW2ilb4MjMT', max_length=32, unique=True, verbose_name='AK'),
        ),
        migrations.AlterField(
            model_name='competencyregistry',
            name='secret_key',
            field=models.CharField(default='A3wPUz3s2WTAbrUhwqUANPPzv24T5MJE', max_length=32, unique=True, verbose_name='SK'),
        ),
    ]
