# Generated by Django 4.2.7 on 2024-01-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceMgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDetectionRecordInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(upload_to='', verbose_name='输入图片')),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='输出图片')),
                ('detection_result', models.TextField(blank=True, null=True, verbose_name='检测结果')),
                ('detection_type', models.SmallIntegerField(choices=[(0, '所有人脸'), (1, '最大人脸'), (2, '置信度最优人脸')], default=0, verbose_name='人脸检测类型')),
                ('status_describe', models.TextField(blank=True, null=True, verbose_name='状态描述')),
                ('request_time', models.DateTimeField(verbose_name='请求时间')),
                ('respond_time', models.DateTimeField(blank=True, null=True, verbose_name='应答时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('request_id', models.CharField(default='88e79448-d9fa-48eb-b006-aa9a2a377c85', max_length=36, verbose_name='请求ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='serviceMgt.competencyregistry', verbose_name='账号')),
            ],
            options={
                'verbose_name': '人脸检测调用记录表',
                'verbose_name_plural': '4.人脸检测调用记录表',
            },
        ),
    ]
