# Generated by Django 4.2.7 on 2024-01-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceDet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedetectionrecordinformation',
            name='request_id',
            field=models.CharField(default='16e92298-7ab3-4810-8338-018aab615603', max_length=36, verbose_name='请求ID'),
        ),
    ]
