# Generated by Django 4.2.7 on 2024-01-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureextractionrecordinformation',
            name='detection_type',
            field=models.BooleanField(choices=[(2, '没有存在人脸信息'), (1, '成功'), (0, '失败')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='featureextractionrecordinformation',
            name='request_id',
            field=models.CharField(default='9ad45040-4f22-4216-b068-1eb0a0eb888d', max_length=36, verbose_name='请求ID'),
        ),
        migrations.AlterField(
            model_name='o2nrecognitionrecordinformation',
            name='o2n_rec_type',
            field=models.SmallIntegerField(choices=[(2, '可能是'), (3, '无匹配信息'), (1, '成功'), (0, '失败')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='o2nrecognitionrecordinformation',
            name='request_id',
            field=models.CharField(default='baa170b4-9f47-4c91-8a00-96311c76f282', max_length=36, verbose_name='请求ID'),
        ),
        migrations.AlterField(
            model_name='o2ocheckrecognitionrecordinformation',
            name='o2o_check_rec_type',
            field=models.SmallIntegerField(choices=[(1, '是同一个人'), (2, '可能是同一个人'), (3, '不是同一个人'), (0, '失败')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='o2ocheckrecognitionrecordinformation',
            name='request_id',
            field=models.CharField(default='029e9d1b-1f46-4ad2-ab1d-5ae77bc8eec1', max_length=36, verbose_name='请求ID'),
        ),
        migrations.AlterField(
            model_name='o2oimagerecognitionrecordinformation',
            name='o2o_image_rec_type',
            field=models.SmallIntegerField(choices=[(1, '是同一个人'), (2, '可能是同一个人'), (3, '不是同一个人'), (0, '失败')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='o2oimagerecognitionrecordinformation',
            name='request_id',
            field=models.CharField(default='8df5e1df-9c9d-4535-8e1d-b0aa702e08e5', max_length=36, verbose_name='请求ID'),
        ),
    ]
